### ISSUE TITLE
game flow

### ISSUE THREAD

**Issue by feliciano98** [cclagodna/goblins-stole-my-bike#10]
1.	The player battles 
2.	The player wins the battle 
Total_gold += (Creature_Base_gold + Base_gold*creature_multilper )*Level_multiplier
Total_experience = Total_expereince + (Base_win_expereince*creature_multiplier )*level_multipler
I wrote these two differently to show how It could be done using += or just
3.	OR the player dies instead
This one should be an if statement instead because the later the game goes the more the player would lose, one lost battle in the late game if there is no if statement used could result in the player losing significant amounts of gold possibly discouraging players.
If(total_gold<1,000,000)
Total_gold = total_gold-(total_gold*x)
Where x is a random double going from 0.05 to 0.09 making the player lose a maxium of 90,000 gold and when they for example only have 2000 gold they can only lose a max of roughly 200 gold. 
ELSE
Total_gold = total_gold-(100,000+player_level*10)
This should still cause the player to lose a decent amount of gold for losing without being discouraging
4.	The player fights the boss and wins
Total_gold += (Creature_Base_gold + Base_gold*creature_multilper )*Level_multiplier + Boss_bouns_gold
5.	The player fights the boss and loses 
Use the normal “death” loss gold formula I put above in 3. 

No experience or items are lost on death but we could add items for them winning battle or even with a chance just watch for the max size of the inventory array and how we add it to the array because it could overwrite or delete items inadvertently from the players inventory.

**Comment by cclagodna** [comment]
Good so far, guys! I know you're aware, but to reiterate, make sure you describe the game loop outside of battle. What can the player do with their gold, experience, and items? If you guys have any other ideas other than battle, shop, and inventory, feel free to throw them in. Maybe we can have something like a power-up station where maybe you allocated stat points to the monster, a capture or evolution mechanic, and so on and so forth.

**Comment by feliciano98** [comment]
This was mostly Done with the base game in mind but to add to it i think id' say a few more things 
1. originally i thought it might be a good idea to keep the player health consistent and have the player rest or use items to  get their health set to full but i think that this would cause  more problems then good because i can easily see the player getting upset if they forget to heal before a battle. 
2. The item shop would be very simple it would be similar to the java grid pane (if im remembering correctly 
0,0 0,1 0,2 0,3
1,0 1,1 1,2 1,3
2,0 2,1 2,2 2,3
We would put the item picture on 0,0
the price on 1,0
and the buy button with the coin price on 2,0
with the button simply adding the item into an array.

All i got for now. im in the middle of class so.. 
yuh.
