### ISSUE TITLE
Sprint - Nov 5th

### ISSUE THREAD

**Issue by cclagodna** [cclagodna/goblins-stole-my-bike#11]
- [ ] Finalize Battling System
    - How does combat work?
    - What formulas should be used?
    - [ ] Implement battle system into program
- [ ] Finalize `monster` Class
    - What stats should there be?
    - What types or "elements" should there be?
- [ ] Finalize `attack` Class
    - How should the math work?
    - What status effects can they inflict, if any?
    - How do elements play into attacks?
    - Should attacks have more attributes, like accuracy, critical chance, etc?
- [ ] Finalize `item` Class
    - What possible effects can they produce?
        - How would these effects be implemented?
    - How should they be acquired?
    - What variables should they have?
- [ ] Finalize `inventory` Class
    - How should items be stored?
        - Should there be a limit?
    - Can items be added, moved, and removed freely?
- [ ] Decide on aesthetics
    - What style and look should the game have?

**Comment by feliciano98** [comment]
i think for items we should start with a health potion item.
