### ISSUE TITLE
Presentation 2 - Oct 22nd

### ISSUE THREAD

**Issue by cclagodna** [cclagodna/goblins-stole-my-bike#13]
- Application Name

- Team Member Names
    - Please do NOT forget to introduce yourself when you speak

- Application Goal
    - Briefly remind the audience the purpose of your project. Is it tracking something or teaching something. Who will be the primary users of your application?

- Discuss your product backlog
    - In the presentation you don’t need to read all of your user stories nor do you need to read every item from your Product backlog. Discuss any major changes from your initial presentation, including additions and deletions.

- Discuss your schedule
    - Discuss you dates and overall goal of each Sprint. Let us know if you’re on schedule,
and if you aren’t what will you do to get back on schedule.

- Discuss challenges
    - Any challenges your team (each member) faced and how you are handling them.

- Demo your project as-is
    - Your team need to demo a portion of the project as is available. At least one project feature needs to be demonstrated by your team during the 1st midterm project presentation. Also, please make sure that your team have special cabling (if needed).

**Comment by KKennedy910** [comment]
https://docs.google.com/presentation/d/1tvDfWQn6oATDQ0MD2mgXoD9KxtcDvJAwru_qS0G6z2Q/edit?usp=sharing
