### ISSUE TITLE
Report 2 - Oct 22nd

### ISSUE THREAD

**Issue by cclagodna** [cclagodna/goblins-stole-my-bike#15]
Your team MUST submit a report on your project that contains the following:

- Group Project Name
- Team Member Names
- Application Goal

- Restate the purpose of your project for the user. Identify who will be the potential users.

- List your product backlog and Sprint schedule:
    - For the Sprints that have passed, current Sprint and next Sprint:
        - List which user stories were assigned in each Sprint, and associated breakdown of tasks (with assignee names) for user stories.
        - If some user stories were started but not completed, detail that.

- For future Sprints
    - List user stories assigned to remaining Sprints
    - List changes, additions and deletions of user stories
        - Detail challenges
        - Detail any challenges your team has faced and how you are handling them
- Provide readable images (and explanations) from tools your team are using for your project, which means In order to be readable you may have to break it into several images:
    - show your complete schedule tracking tool, such as a full image of your Trello board
    - show how your team are doing version control on the code, such as images from Github
    - show other tools being used by your team in a sample, such as Google docs
    - Include any images that will demonstrate the use of tools by your team
- List any references (e.g., books, papers, websites from which you adopt some code from)
your team used so far. YES, you are allowed to adopt code from the internet or even use
it directly to your project, but listing the sources is necessary.

**Comment by cclagodna** [comment]
[Project Report 10.22.docx](https://github.com/cclagodna/goblins-stole-my-bike/files/3752407/Project.Report.10.22.docx)

**Comment by KKennedy910** [comment]
https://docs.google.com/presentation/d/1tvDfWQn6oATDQ0MD2mgXoD9KxtcDvJAwru_qS0G6z2Q/edit?usp=sharing
